### ISSUE TITLE
[BUG] - Incorrect validation of a specific registration number

### ISSUE THREAD

**Issue by frebos88** [organisationsnummer/js#175]
**Context**

The registration number 559248-0001 (masked) is a legit and registered Aktiebolag but not valid according to the organisationsnummer library.

**Expected outcome**

That the organisation number is valid and parsed correctly since it's a company that is registered (2020) and active with two years of company reports behind it.

**Actual outcome**

Not valid, exception is thrown on parse.

**Description**

**Minimal reproducible test case**

Just type it into [organisationsnumber.dev](https://organisationsnummer.dev/) and see that it is not valid. I presume it to be the regex that doesn't like a tripple 0. Nothing is being matched by the regex. You can reach out to me privately if you want the actual company registration number in question.

<img width="1140" alt="Screenshot 2022-12-27 at 12 23 07" src="https://user-images.githubusercontent.com/7260259/209659598-ff8ee325-0fc6-4b7b-878a-3394ca1049c1.png">

**Comment by frozzare** [comment]
Thanks for your bug report, i'll look into this and would appreciate if you can send me the company registration number. You can find my contact details here https://frozzare.com/

**Comment by frebos88** [comment]
I managed to find the company again and sent you a mail with the details, hopefully it is useful. 👍
